### ISSUE TITLE
Delete in-memory cache using wildcard character in cache key pattern

### ISSUE THREAD

**Issue by jpotrebic** [mkozjak/koa-cache-lite#22]
Redis cache type has an option to delete several items from cache when deleting by key,
for example sending cache.clear('*shop') would delete all cache items with keys ending in 'shop', not only exact matched keys.

Is it possible to have the same functionality for in-memory cache?

From what I can tell, wildcard characters are currently ignored:
koa-cache-lite/lib/drivers/memory.js, ln 66 and ln 75
`patternKeys.push(key.replace('*', ''))`

**Comment by mkozjak** [comment]
@toppyoushimonai: Yup, this was not implemented in the first place because Map.has() doesn't accept regex as a parameter. I would need to implement the search on my own. Will be done shortly.
