### ISSUE TITLE
Error when deleting with a key containing wildcard character (clear('*bla'))

### ISSUE THREAD

**Issue by jpotrebic** [mkozjak/koa-cache-lite#23]
I get an error when trying to delete from redis cache using a wildcard character if there is no match in keys, for example:

> debug: deleting from redis cache 
> { '0': 'proxy:_bla',
>   '1': 'proxy:_bla:_',
>   '2': 'proxy:_bla?_',
>   '3': 'proxy:_bla#*' }
> Unhandled rejection ReplyError: ERR wrong number of arguments for 'del' command
>     at ReplyParser._parseResult (home/proxy/node_modules/ioredis/lib/parsers/javascript.js:39:14)
>     at ReplyParser.execute (/home/proxy/node_modules/ioredis/lib/parsers/javascript.js:139:20)
>     at Socket.<anonymous> (/home/proxy/node_modules/ioredis/lib/redis/event_handler.js:94:22)
>     at emitOne (events.js:90:13)
>     at Socket.emit (events.js:182:7)
>     at readableAddChunk (_stream_readable.js:153:18)
>     at Socket.Readable.push (_stream_readable.js:111:10)
>     at TCP.onread (net.js:529:20)

Should check if deleteKeys is an empty array before attempting delete?

**Comment by mkozjak** [comment]
Should do a recursive check here if Array arrived: https://github.com/mkozjak/koa-cache-lite/blob/master/lib/drivers/redis.js#L104

**Comment by mkozjak** [comment]
Actually, I cannot reproduce that. Here's the example code:

``` js
var koa = require('koa')()
var router = require('koa-router')()
var cache = require('./index')

router.get('/api/v1/test', function *(next) {
  this.body = '#@$$g23g23gqf23g332g3g23gf32g2fewvweg'

  setTimeout(function() {
    cache.clear('*bla')
  }, 2000)
})

cache.configure({
  '/api/v1/test': 3000000
}, {
  external: {
    type: 'redis'
  },
  cacheKeyPrefix: 'proxy',
  minimumLength: 20,
  debug: true
})

koa.use(cache.middleware())
koa.use(router.routes())

koa.listen(1337)

```

Log output:

```
deleting from redis cache [ 'proxy:*bla', 'proxy:*bla:*', 'proxy:*bla?*', 'proxy:*bla#*' ]
```

It's strange that the debug message wrote out an object instead of an array in your case.
Which node, ioredis and redis-server versions are you testing on?
