### ISSUE TITLE
regex doesn't support '-'

### ISSUE THREAD

**Issue by ironsweet** [mkozjak/koa-cache-lite#26]
The generated regex doesn't cover '-' in URL. E.g.,
/api/jobs/:id -> /^\/api\/jobs\/[A-z0-9]+(?:\/)?$/

But it doesn't catch /api/jobs/2016-1

**Comment by mkozjak** [comment]
@balzaczyy: Thanks for reporting. Should be fixed in 3.4.2, which is now published.
